services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/config.ini:/etc/grafana/grafana.ini
      - ${DASHBOARDS_DIRECTORY}:/var/lib/grafana/dashboards
